# GeoGebra applet interaction from Python

In [49]:
# this magic for develop only
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [18]:
import xml.etree.ElementTree as ET
import xmlschema
import base64
import polars as pl

In [10]:
from ggblab import GeoGebra

In [11]:
# open GeoGebra Widget on left-side
ggb = await GeoGebra().init()

Using local cached file: xsd/common.xsd

In [12]:
# load from .ggb (zipped, and base64 encoded)
c = ggb.file.load('Kepler Halley.ggb')

In [13]:
# sending loaded construction to GeoGebra view and draw
r = await ggb.function("setBase64", [ggb.construction.base64_buffer.decode('utf-8')])

In [12]:
import ipykernel
import re
# カーネルの接続情報ファイルパスを取得
connection_file = ipykernel.connect.get_connection_file()
# ファイル名からカーネルID（UUID）を抽出
kernel_id = re.search('kernel-(.*).json', connection_file).group(1)
print(kernel_id)

b4595391-62eb-40ff-b107-0f8231ea2539

In [9]:
r = await ggb.function("showAlgebraInput", [False])

In [50]:
r = await ggb.function("getPerspectiveXML")
print(r)

<perspective id="tmp">
	<panes>
	<pane location="" divider="0.06558849955076371" orientation="1"/>
</panes>
	<views>
	<view id="4097" visible="false" inframe="false" stylebar="true" location="1,1,1,1" size="400" window="100,100,700,550"/>
	<view id="512" toolbar="0 | 1 501 5 19 , 67 | 2 15 45 18 , 7 37 | 514 3 9 , 13 44 , 47 | 16 51 | 551 550 11 ,  20 22 21 23 , 55 56 57 , 12 | 69 | 510 511 , 512 513 | 533 531 , 534 532 , 522 523 , 537 536 , 535 , 538 | 521 520 | 36 , 38 49 560 | 571 30 29 570 31 33 | 17 | 540 40 41 42 , 27 28 35 , 6 , 502" visible="false" inframe="false" stylebar="false" location="1,1,1" size="500" window="100,100,600,400"/>
	<view id="4" toolbar="0 || 2020 , 2021 , 2022 || 2001 , 2003 , 2002 , 2004 , 2005 || 2040 , 2041 , 2042 , 2044 , 2043" visible="false" inframe="false" stylebar="false" location="1,1" size="300" window="100,100,600,400"/>
	<view id="8" toolbar="1001 | 1002 | 1003  || 1005 | 1004 || 1006 | 1007 | 1010 || 1008 | 1009 || 6" visible="false" inframe="false" stylebar="false" location="1,3" size="300" window="100,100,600,400"/>
	<view id="1" visible="true" inframe="false" stylebar="false" location="1" size="1042" window="100,100,600,400"/>
	<view id="16" visible="false" inframe="false" stylebar="false" location="1" size="300" window="50,50,500,500"/>
	<view id="32" visible="false" inframe="false" stylebar="true" location="1" size="608" window="50,50,500,500"/>
	<view id="64" visible="false" inframe="false" stylebar="false" location="1" size="480" window="50,50,500,500"/>
	<view id="128" visible="false" inframe="false" stylebar="false" location="1" size="480" window="50,50,500,500"/>
	<view id="70" toolbar="0 || 2020 || 2021 || 2022" visible="false" inframe="false" stylebar="true" location="1" size="900" window="50,50,500,500"/>
	<view id="2" visible="false" inframe="false" stylebar="false" location="2" size="200" tab="TOOLS" window="100,100,250,400"/>
</views>
	<toolbar show="true" items="0 77 73 62 | 1 501 67 , 5 19 , 72 75 76 | 2 15 45 , 18 65 , 7 37 | 4 3 8 9 , 13 44 , 58 , 47 | 16 51 64 , 70 | 10 34 53 11 , 24  20 22 , 21 23 | 55 56 57 , 12 | 36 46 , 38 49  50 , 71  14  68 | 30 29 54 32 31 33 | 25 17 26 60 52 61 | 40 41 42 , 27 28 35 , 6" position="1" help="false"/>
	<input show="false" cmd="true" top="algebra"/>
	<dockBar show="false" east="false"/>
</perspective>

In [47]:
r = await ggb.function("setGridVisible", [1, False])
print(r)

None

In [49]:
r = await ggb.function("getGraphicsOptions", [1])
r

{'rightAngleStyle': 1,
 'pointCapturing': 3,
 'grid': False,
 'gridIsBold': False,
 'gridType': 3,
 'bgColor': '#FFFFFF',
 'gridColor': '#C0C0C0',
 'axesColor': '#252525',
 'rulerType': 0,
 'axes': {'x': {'visible': False,
   'positiveAxis': False,
   'showNumbers': True,
   'tickStyle': 1,
   'label': None,
   'unitLabel': None},
  'y': {'visible': False,
   'positiveAxis': False,
   'showNumbers': True,
   'tickStyle': 1,
   'label': None,
   'unitLabel': None},
  'z': {'visible': True,
   'positiveAxis': False,
   'showNumbers': True,
   'tickStyle': 1,
   'label': None,
   'unitLabel': None}},
 'gridDistance': {'x': None, 'y': None}}

In [40]:
r = await ggb.function("getEditorState")
r

'{"content":"eq1: x^(2)+y^(2)=1","caret":[12]}'

In [43]:
r = await ggb.function("setWidth", [800])
r

In [14]:
from ggblab_extra.construction_io import ConstructionIO

In [15]:
df = await ConstructionIO.initialize_dataframe(ggb, use_applet=True)

In [24]:
df.filter(pl.col("Layer").is_in([9, 0]))["Type", "Name", "Command", "Value"]

shape: (11, 4)
┌───────────────────────┬────────┬────────────────────────┬─────────────────────────────────┐
│ Type                  ┆ Name   ┆ Command                ┆ Value                           │
│ ---                   ┆ ---    ┆ ---                    ┆ ---                             │
│ str                   ┆ str    ┆ str                    ┆ str                             │
╞═══════════════════════╪════════╪════════════════════════╪═════════════════════════════════╡
│ numeric               ┆ G      ┆ null                   ┆ G = 1                           │
│ numeric               ┆ M      ┆ null                   ┆ M = 1                           │
│ multivariablefunction ┆ x'     ┆ null                   ┆ x'(t, x, y, vx, vy) = vx        │
│ numeric               ┆ m      ┆ 2                      ┆ m = 2                           │
│ multivariablefunction ┆ y''    ┆ -((G M y) / (sqrt(x² + ┆ y''(t, x, y, dx, dy) = -((1 * … │
│                       ┆        ┆ y²))^(1…               ┆                                 │
│ multivariablefunction ┆ x''    ┆ -((G M x) / (sqrt(x² + ┆ x''(t, x, y, dx, dy) = -((1 * … │
│                       ┆        ┆ y²))^(1…               ┆                                 │
│ multivariablefunction ┆ y'     ┆ null                   ┆ y'(t, x, y, dx, dy) = dy        │
│ numeric               ┆ s      ┆ null                   ┆ s = 0.0812                      │
│ numeric               ┆ vy_{0} ┆ 1.821                  ┆ vy_{0} = 1.821                  │
│ numeric               ┆ x_{0}  ┆ 0.5928                 ┆ x_{0} = 0.5928                  │
│ numeric               ┆ h      ┆ 451                    ┆ h = 451                         │
└───────────────────────┴────────┴────────────────────────┴─────────────────────────────────┘

In [21]:
ConstructionIO.save_dataframe(p.df, ggb=ggb, fmt='json')

'2025_01_01_2.json'

In [10]:
import networkx as nx

In [24]:
from ggblab_extra.construction_parser import ConstructionTreeParser

In [12]:
p = ConstructionTreeParser(df)

In [13]:
g1 = p.parse()

In [22]:
p.df

shape: (24, 12)
┌──────────┬──────┬──────────┬─────────────┬───┬───────────┬───────────┬─────────────┬─────────────┐
│ Sequence ┆ Name ┆ Type     ┆ Command     ┆ … ┆ ShowLabel ┆ Auxiliary ┆ DependsOn   ┆ DependsOn_m │
│ ---      ┆ ---  ┆ ---      ┆ ---         ┆   ┆ ---       ┆ ---       ┆ ---         ┆ inimal      │
│ u32      ┆ str  ┆ str      ┆ str         ┆   ┆ bool      ┆ bool      ┆ list[str]   ┆ ---         │
│          ┆      ┆          ┆             ┆   ┆           ┆           ┆             ┆ list[str]   │
╞══════════╪══════╪══════════╪═════════════╪═══╪═══════════╪═══════════╪═════════════╪═════════════╡
│ 0        ┆ eq1  ┆ circle   ┆ x² + y² = 1 ┆ … ┆ false     ┆ false     ┆ []          ┆ []          │
│ 1        ┆ O    ┆ point    ┆ Center(eq1) ┆ … ┆ true      ┆ false     ┆ ["eq1"]     ┆ ["eq1"]     │
│ 2        ┆ P    ┆ point    ┆ Point(eq1)  ┆ … ┆ true      ┆ false     ┆ ["eq1"]     ┆ ["eq1"]     │
│ 3        ┆ f    ┆ line     ┆ Line(O, P)  ┆ … ┆ false     ┆ false     ┆ ["O", "P",  ┆ ["O", "P"]  │
│          ┆      ┆          ┆             ┆   ┆           ┆           ┆ "eq1"]      ┆             │
│ 4        ┆ A    ┆ point    ┆ Intersect(e ┆ … ┆ true      ┆ false     ┆ ["O", "P",  ┆ ["eq1",     │
│          ┆      ┆          ┆ q1, f)      ┆   ┆           ┆           ┆ … "f"]      ┆ "f"]        │
│ 5        ┆ B    ┆ point    ┆ Intersect(e ┆ … ┆ true      ┆ false     ┆ ["O", "P",  ┆ ["eq1",     │
│          ┆      ┆          ┆ q1, f)      ┆   ┆           ┆           ┆ … "f"]      ┆ "f"]        │
│ 6        ┆ C    ┆ point    ┆ Point(f)    ┆ … ┆ true      ┆ false     ┆ ["O", "P",  ┆ ["f"]       │
│          ┆      ┆          ┆             ┆   ┆           ┆           ┆ … "f"]      ┆             │
│ 7        ┆ g    ┆ line     ┆ Perpendicul ┆ … ┆ false     ┆ false     ┆ ["C", "O",  ┆ ["C"]       │
│          ┆      ┆          ┆ arLine(C,   ┆   ┆           ┆           ┆ … "f"]      ┆             │
│          ┆      ┆          ┆ f)          ┆   ┆           ┆           ┆             ┆             │
│ 8        ┆ E    ┆ point    ┆ Intersect(e ┆ … ┆ true      ┆ false     ┆ ["C", "O",  ┆ ["g"]       │
│          ┆      ┆          ┆ q1, g)      ┆   ┆           ┆           ┆ … "g"]      ┆             │
│ 9        ┆ D    ┆ point    ┆ Intersect(e ┆ … ┆ true      ┆ false     ┆ ["C", "O",  ┆ ["g"]       │
│          ┆      ┆          ┆ q1, g)      ┆   ┆           ┆           ┆ … "g"]      ┆             │
│ 10       ┆ t1   ┆ triangle ┆ Polygon(O,  ┆ … ┆ false     ┆ false     ┆ ["C", "D",  ┆ ["D", "E",  │
│          ┆      ┆          ┆ D, E)       ┆   ┆           ┆           ┆ … "g"]      ┆ "O"]        │
│ 11       ┆ e    ┆ segment  ┆ Segment(O,  ┆ … ┆ false     ┆ true      ┆ ["C", "D",  ┆ ["D", "O",  │
│          ┆      ┆          ┆ D, t1)      ┆   ┆           ┆           ┆ … "t1"]     ┆ "t1"]       │
│ 12       ┆ o    ┆ segment  ┆ Segment(D,  ┆ … ┆ false     ┆ true      ┆ ["C", "D",  ┆ ["D", "E",  │
│          ┆      ┆          ┆ E, t1)      ┆   ┆           ┆           ┆ … "t1"]     ┆ "t1"]       │
│ 13       ┆ d    ┆ segment  ┆ Segment(E,  ┆ … ┆ false     ┆ true      ┆ ["C", "D",  ┆ ["E", "O",  │
│          ┆      ┆          ┆ O, t1)      ┆   ┆           ┆           ┆ … "t1"]     ┆ "t1"]       │
│ 14       ┆ a    ┆ boolean  ┆ AreEqual(Di ┆ … ┆ true      ┆ false     ┆ []          ┆ []          │
│          ┆      ┆          ┆ stance(O,   ┆   ┆           ┆           ┆             ┆             │
│          ┆      ┆          ┆ D), Dista…  ┆   ┆           ┆           ┆             ┆             │
│ 15       ┆ b    ┆ boolean  ┆ AreEqual(An ┆ … ┆ true      ┆ false     ┆ []          ┆ []          │
│          ┆      ┆          ┆ gle(O, D,   ┆   ┆           ┆           ┆             ┆             │
│          ┆      ┆          ┆ E), Angle…  ┆   ┆           ┆           ┆             ┆             │
│ 16       ┆ O'   ┆ point    ┆ Reflect(O,  ┆ … ┆ true      ┆ false     ┆ ["O", "P",  ┆ ["f"]       │
│          ┆      ┆          ┆ f)          ┆   ┆           ┆           ┆ … "f"]      ┆             │
│ 17       ┆ C'   ┆ point    ┆ Reflect(C,  ┆ … ┆ true      ┆ false     ┆ ["C", "O",  ┆ ["C"]       │
│          ┆      ┆          ┆ f)          ┆   ┆           ┆           ┆ … "f"]      ┆             │
│ 18       ┆ E'   ┆ point    ┆ Reflect(E,  ┆ … ┆ true      ┆ false     ┆ ["C", "E",  ┆ ["E"]       │
│          ┆      ┆          ┆ f)          ┆   ┆           ┆           ┆ … "g"]      ┆             │
│ 19       ┆ t2   ┆ triangle ┆ Polygon(O', ┆ … ┆ false     ┆ false     ┆ ["C", "C'", ┆ ["C'",      │
│          ┆      ┆          ┆ C', E')     ┆   ┆           ┆           ┆ … "g"]      ┆ "E'", "O'"] │
│ 20       ┆ e'   ┆ segment  ┆ Segment(O', ┆ … ┆ false     ┆ true      ┆ ["C", "C'", ┆ ["C'",      │
│          ┆      ┆          ┆ C', t2)     ┆   ┆           ┆           ┆ … "t2"]     ┆ "O'", "t2"] │
│ 21       ┆ o'   ┆ segment  ┆ Segment(C', ┆ … ┆ false     ┆ true      ┆ ["C", "C'", ┆ ["C'",      │
│          ┆      ┆          ┆ E', t2)     ┆   ┆           ┆           ┆ … "t2"]     ┆ "E'", "t2"] │
│ 22       ┆ c'   ┆ segment  ┆ Segment(E', ┆ … ┆ false     ┆ true      ┆ ["C", "C'", ┆ ["E'",      │
│          ┆      ┆          ┆ O', t2)     ┆   ┆           ┆           ┆ … "t2"]     ┆ "O'", "t2"] │
│ 23       ┆ c    ┆ boolean  ┆ AreEqual(D, ┆ … ┆ true      ┆ false     ┆ []          ┆ []          │
│          ┆      ┆          ┆ E')         ┆   ┆           ┆           ┆             ┆             │
└──────────┴──────┴──────────┴─────────────┴───┴───────────┴───────────┴─────────────┴─────────────┘

In [15]:
nx.write_network_text(g1)

╙── eq1
    ├─╼ O
    │   ├─╼ f ╾ P
    │   │   ├─╼ A ╾ eq1
    │   │   ├─╼ B ╾ eq1
    │   │   ├─╼ C
    │   │   │   ├─╼ g ╾ f
    │   │   │   │   ├─╼ E ╾ eq1
    │   │   │   │   │   ├─╼ t1 ╾ O, D
    │   │   │   │   │   │   ├─╼ e ╾ O, D
    │   │   │   │   │   │   ├─╼ o ╾ D, E
    │   │   │   │   │   │   └─╼ d ╾ E, O
    │   │   │   │   │   ├─╼ E' ╾ f
    │   │   │   │   │   │   ├─╼ t2 ╾ O', C'
    │   │   │   │   │   │   │   ├─╼ e' ╾ O', C'
    │   │   │   │   │   │   │   ├─╼ o' ╾ C', E'
    │   │   │   │   │   │   │   └─╼ c' ╾ E', O'
    │   │   │   │   │   │   └─╼  ...
    │   │   │   │   │   └─╼  ...
    │   │   │   │   └─╼ D ╾ eq1
    │   │   │   │       └─╼  ...
    │   │   │   └─╼ C' ╾ f
    │   │   │       └─╼  ...
    │   │   ├─╼ O' ╾ O
    │   │   │   └─╼  ...
    │   │   └─╼  ...
    │   └─╼  ...
    ├─╼ P
    │   └─╼  ...
    └─╼  ...

In [38]:
g2 = p.parse_subgraph_legacy()

In [17]:
p.df

shape: (24, 12)
┌──────────┬──────┬──────────┬─────────────┬───┬───────────┬───────────┬─────────────┬─────────────┐
│ Sequence ┆ Name ┆ Type     ┆ Command     ┆ … ┆ ShowLabel ┆ Auxiliary ┆ DependsOn   ┆ DependsOn_m │
│ ---      ┆ ---  ┆ ---      ┆ ---         ┆   ┆ ---       ┆ ---       ┆ ---         ┆ inimal      │
│ u32      ┆ str  ┆ str      ┆ str         ┆   ┆ bool      ┆ bool      ┆ list[str]   ┆ ---         │
│          ┆      ┆          ┆             ┆   ┆           ┆           ┆             ┆ list[str]   │
╞══════════╪══════╪══════════╪═════════════╪═══╪═══════════╪═══════════╪═════════════╪═════════════╡
│ 0        ┆ eq1  ┆ circle   ┆ x² + y² = 1 ┆ … ┆ false     ┆ false     ┆ []          ┆ []          │
│ 1        ┆ O    ┆ point    ┆ Center(eq1) ┆ … ┆ true      ┆ false     ┆ ["eq1"]     ┆ ["eq1"]     │
│ 2        ┆ P    ┆ point    ┆ Point(eq1)  ┆ … ┆ true      ┆ false     ┆ ["eq1"]     ┆ ["eq1"]     │
│ 3        ┆ f    ┆ line     ┆ Line(O, P)  ┆ … ┆ false     ┆ false     ┆ ["O", "P",  ┆ ["O", "P"]  │
│          ┆      ┆          ┆             ┆   ┆           ┆           ┆ "eq1"]      ┆             │
│ 4        ┆ A    ┆ point    ┆ Intersect(e ┆ … ┆ true      ┆ false     ┆ ["O", "P",  ┆ ["eq1",     │
│          ┆      ┆          ┆ q1, f)      ┆   ┆           ┆           ┆ … "f"]      ┆ "f"]        │
│ 5        ┆ B    ┆ point    ┆ Intersect(e ┆ … ┆ true      ┆ false     ┆ ["O", "P",  ┆ ["eq1",     │
│          ┆      ┆          ┆ q1, f)      ┆   ┆           ┆           ┆ … "f"]      ┆ "f"]        │
│ 6        ┆ C    ┆ point    ┆ Point(f)    ┆ … ┆ true      ┆ false     ┆ ["O", "P",  ┆ ["f"]       │
│          ┆      ┆          ┆             ┆   ┆           ┆           ┆ … "f"]      ┆             │
│ 7        ┆ g    ┆ line     ┆ Perpendicul ┆ … ┆ false     ┆ false     ┆ ["C", "O",  ┆ ["C"]       │
│          ┆      ┆          ┆ arLine(C,   ┆   ┆           ┆           ┆ … "f"]      ┆             │
│          ┆      ┆          ┆ f)          ┆   ┆           ┆           ┆             ┆             │
│ 8        ┆ E    ┆ point    ┆ Intersect(e ┆ … ┆ true      ┆ false     ┆ ["C", "O",  ┆ ["g"]       │
│          ┆      ┆          ┆ q1, g)      ┆   ┆           ┆           ┆ … "g"]      ┆             │
│ 9        ┆ D    ┆ point    ┆ Intersect(e ┆ … ┆ true      ┆ false     ┆ ["C", "O",  ┆ ["g"]       │
│          ┆      ┆          ┆ q1, g)      ┆   ┆           ┆           ┆ … "g"]      ┆             │
│ 10       ┆ t1   ┆ triangle ┆ Polygon(O,  ┆ … ┆ false     ┆ false     ┆ ["C", "D",  ┆ ["D", "E",  │
│          ┆      ┆          ┆ D, E)       ┆   ┆           ┆           ┆ … "g"]      ┆ "O"]        │
│ 11       ┆ e    ┆ segment  ┆ Segment(O,  ┆ … ┆ false     ┆ true      ┆ ["C", "D",  ┆ ["D", "O",  │
│          ┆      ┆          ┆ D, t1)      ┆   ┆           ┆           ┆ … "t1"]     ┆ "t1"]       │
│ 12       ┆ o    ┆ segment  ┆ Segment(D,  ┆ … ┆ false     ┆ true      ┆ ["C", "D",  ┆ ["D", "E",  │
│          ┆      ┆          ┆ E, t1)      ┆   ┆           ┆           ┆ … "t1"]     ┆ "t1"]       │
│ 13       ┆ d    ┆ segment  ┆ Segment(E,  ┆ … ┆ false     ┆ true      ┆ ["C", "D",  ┆ ["E", "O",  │
│          ┆      ┆          ┆ O, t1)      ┆   ┆           ┆           ┆ … "t1"]     ┆ "t1"]       │
│ 14       ┆ a    ┆ boolean  ┆ AreEqual(Di ┆ … ┆ true      ┆ false     ┆ []          ┆ []          │
│          ┆      ┆          ┆ stance(O,   ┆   ┆           ┆           ┆             ┆             │
│          ┆      ┆          ┆ D), Dista…  ┆   ┆           ┆           ┆             ┆             │
│ 15       ┆ b    ┆ boolean  ┆ AreEqual(An ┆ … ┆ true      ┆ false     ┆ []          ┆ []          │
│          ┆      ┆          ┆ gle(O, D,   ┆   ┆           ┆           ┆             ┆             │
│          ┆      ┆          ┆ E), Angle…  ┆   ┆           ┆           ┆             ┆             │
│ 16       ┆ O'   ┆ point    ┆ Reflect(O,  ┆ … ┆ true      ┆ false     ┆ ["O", "P",  ┆ ["f"]       │
│          ┆      ┆          ┆ f)          ┆   ┆           ┆           ┆ … "f"]      ┆             │
│ 17       ┆ C'   ┆ point    ┆ Reflect(C,  ┆ … ┆ true      ┆ false     ┆ ["C", "O",  ┆ ["C"]       │
│          ┆      ┆          ┆ f)          ┆   ┆           ┆           ┆ … "f"]      ┆             │
│ 18       ┆ E'   ┆ point    ┆ Reflect(E,  ┆ … ┆ true      ┆ false     ┆ ["C", "E",  ┆ ["E"]       │
│          ┆      ┆          ┆ f)          ┆   ┆           ┆           ┆ … "g"]      ┆             │
│ 19       ┆ t2   ┆ triangle ┆ Polygon(O', ┆ … ┆ false     ┆ false     ┆ ["C", "C'", ┆ ["C'",      │
│          ┆      ┆          ┆ C', E')     ┆   ┆           ┆           ┆ … "g"]      ┆ "E'", "O'"] │
│ 20       ┆ e'   ┆ segment  ┆ Segment(O', ┆ … ┆ false     ┆ true      ┆ ["C", "C'", ┆ ["C'",      │
│          ┆      ┆          ┆ C', t2)     ┆   ┆           ┆           ┆ … "t2"]     ┆ "O'", "t2"] │
│ 21       ┆ o'   ┆ segment  ┆ Segment(C', ┆ … ┆ false     ┆ true      ┆ ["C", "C'", ┆ ["C'",      │
│          ┆      ┆          ┆ E', t2)     ┆   ┆           ┆           ┆ … "t2"]     ┆ "E'", "t2"] │
│ 22       ┆ c'   ┆ segment  ┆ Segment(E', ┆ … ┆ false     ┆ true      ┆ ["C", "C'", ┆ ["E'",      │
│          ┆      ┆          ┆ O', t2)     ┆   ┆           ┆           ┆ … "t2"]     ┆ "O'", "t2"] │
│ 23       ┆ c    ┆ boolean  ┆ AreEqual(D, ┆ … ┆ true      ┆ false     ┆ []          ┆ []          │
│          ┆      ┆          ┆ E')         ┆   ┆           ┆           ┆             ┆             │
└──────────┴──────┴──────────┴─────────────┴───┴───────────┴───────────┴─────────────┴─────────────┘

In [39]:
nx.write_network_text(g2)

╙── eq1
    ├─╼ P
    │   └─╼ f ╾ O
    │       ├─╼ O'
    │       └─╼ C
    │           ├─╼ g
    │           │   ├─╼ E
    │           │   │   └─╼ E'
    │           │   └─╼ D
    │           └─╼ C'
    └─╼ O
        └─╼  ...

In [19]:
labels_map = {}
for n in p.ft:
    if n in g2:
        labels_map[n] = f"[{n}: {len(nx.descendants(g1, n))}]"

In [20]:
nx.set_node_attributes(g1, labels_map, "label")
nx.write_network_text(g1, with_labels="label")

╙── [eq1: 20]
    ├─╼ [O: 18]
    │   ├─╼ [f: 17] ╾ [P: 18]
    │   │   ├─╼ A ╾ [eq1: 20]
    │   │   ├─╼ B ╾ [eq1: 20]
    │   │   ├─╼ [C: 13]
    │   │   │   ├─╼ [g: 11] ╾ [f: 17]
    │   │   │   │   ├─╼ [E: 9] ╾ [eq1: 20]
    │   │   │   │   │   ├─╼ t1 ╾ [O: 18], [D: 4]
    │   │   │   │   │   │   ├─╼ e ╾ [O: 18], [D: 4]
    │   │   │   │   │   │   ├─╼ o ╾ [D: 4], [E: 9]
    │   │   │   │   │   │   └─╼ d ╾ [E: 9], [O: 18]
    │   │   │   │   │   ├─╼ [E': 4] ╾ [f: 17]
    │   │   │   │   │   │   ├─╼ t2 ╾ [O': 4], [C': 4]
    │   │   │   │   │   │   │   ├─╼ e' ╾ [O': 4], [C': 4]
    │   │   │   │   │   │   │   ├─╼ o' ╾ [C': 4], [E': 4]
    │   │   │   │   │   │   │   └─╼ c' ╾ [E': 4], [O': 4]
    │   │   │   │   │   │   └─╼  ...
    │   │   │   │   │   └─╼  ...
    │   │   │   │   └─╼ [D: 4] ╾ [eq1: 20]
    │   │   │   │       └─╼  ...
    │   │   │   └─╼ [C': 4] ╾ [f: 17]
    │   │   │       └─╼  ...
    │   │   ├─╼ [O': 4] ╾ [O: 18]
    │   │   │   └─╼  ...
    │   │   └─╼  ...
    │   └─╼  ...
    ├─╼ [P: 18]
    │   └─╼  ...
    └─╼  ...

In [31]:
from ggblab_extra.construction_parser import build_graph_from_df

In [30]:
p.df

shape: (24, 12)
┌──────────┬──────┬──────────┬─────────────┬───┬───────────┬───────────┬─────────────┬─────────────┐
│ Sequence ┆ Name ┆ Type     ┆ Command     ┆ … ┆ ShowLabel ┆ Auxiliary ┆ DependsOn   ┆ DependsOn_m │
│ ---      ┆ ---  ┆ ---      ┆ ---         ┆   ┆ ---       ┆ ---       ┆ ---         ┆ inimal      │
│ u32      ┆ str  ┆ str      ┆ str         ┆   ┆ bool      ┆ bool      ┆ list[str]   ┆ ---         │
│          ┆      ┆          ┆             ┆   ┆           ┆           ┆             ┆ list[str]   │
╞══════════╪══════╪══════════╪═════════════╪═══╪═══════════╪═══════════╪═════════════╪═════════════╡
│ 0        ┆ eq1  ┆ circle   ┆ x² + y² = 1 ┆ … ┆ false     ┆ false     ┆ []          ┆ []          │
│ 1        ┆ O    ┆ point    ┆ Center(eq1) ┆ … ┆ true      ┆ false     ┆ ["eq1"]     ┆ ["eq1"]     │
│ 2        ┆ P    ┆ point    ┆ Point(eq1)  ┆ … ┆ true      ┆ false     ┆ ["eq1"]     ┆ ["eq1"]     │
│ 3        ┆ f    ┆ line     ┆ Line(O, P)  ┆ … ┆ false     ┆ false     ┆ ["O", "P",  ┆ ["O", "P"]  │
│          ┆      ┆          ┆             ┆   ┆           ┆           ┆ "eq1"]      ┆             │
│ 4        ┆ A    ┆ point    ┆ Intersect(e ┆ … ┆ true      ┆ false     ┆ ["O", "P",  ┆ ["eq1",     │
│          ┆      ┆          ┆ q1, f)      ┆   ┆           ┆           ┆ … "f"]      ┆ "f"]        │
│ 5        ┆ B    ┆ point    ┆ Intersect(e ┆ … ┆ true      ┆ false     ┆ ["O", "P",  ┆ ["eq1",     │
│          ┆      ┆          ┆ q1, f)      ┆   ┆           ┆           ┆ … "f"]      ┆ "f"]        │
│ 6        ┆ C    ┆ point    ┆ Point(f)    ┆ … ┆ true      ┆ false     ┆ ["O", "P",  ┆ ["f"]       │
│          ┆      ┆          ┆             ┆   ┆           ┆           ┆ … "f"]      ┆             │
│ 7        ┆ g    ┆ line     ┆ Perpendicul ┆ … ┆ false     ┆ false     ┆ ["C", "O",  ┆ ["C"]       │
│          ┆      ┆          ┆ arLine(C,   ┆   ┆           ┆           ┆ … "f"]      ┆             │
│          ┆      ┆          ┆ f)          ┆   ┆           ┆           ┆             ┆             │
│ 8        ┆ E    ┆ point    ┆ Intersect(e ┆ … ┆ true      ┆ false     ┆ ["C", "O",  ┆ ["g"]       │
│          ┆      ┆          ┆ q1, g)      ┆   ┆           ┆           ┆ … "g"]      ┆             │
│ 9        ┆ D    ┆ point    ┆ Intersect(e ┆ … ┆ true      ┆ false     ┆ ["C", "O",  ┆ ["g"]       │
│          ┆      ┆          ┆ q1, g)      ┆   ┆           ┆           ┆ … "g"]      ┆             │
│ 10       ┆ t1   ┆ triangle ┆ Polygon(O,  ┆ … ┆ false     ┆ false     ┆ ["C", "D",  ┆ ["D", "E",  │
│          ┆      ┆          ┆ D, E)       ┆   ┆           ┆           ┆ … "g"]      ┆ "O"]        │
│ 11       ┆ e    ┆ segment  ┆ Segment(O,  ┆ … ┆ false     ┆ true      ┆ ["C", "D",  ┆ ["D", "O",  │
│          ┆      ┆          ┆ D, t1)      ┆   ┆           ┆           ┆ … "t1"]     ┆ "t1"]       │
│ 12       ┆ o    ┆ segment  ┆ Segment(D,  ┆ … ┆ false     ┆ true      ┆ ["C", "D",  ┆ ["D", "E",  │
│          ┆      ┆          ┆ E, t1)      ┆   ┆           ┆           ┆ … "t1"]     ┆ "t1"]       │
│ 13       ┆ d    ┆ segment  ┆ Segment(E,  ┆ … ┆ false     ┆ true      ┆ ["C", "D",  ┆ ["E", "O",  │
│          ┆      ┆          ┆ O, t1)      ┆   ┆           ┆           ┆ … "t1"]     ┆ "t1"]       │
│ 14       ┆ a    ┆ boolean  ┆ AreEqual(Di ┆ … ┆ true      ┆ false     ┆ []          ┆ []          │
│          ┆      ┆          ┆ stance(O,   ┆   ┆           ┆           ┆             ┆             │
│          ┆      ┆          ┆ D), Dista…  ┆   ┆           ┆           ┆             ┆             │
│ 15       ┆ b    ┆ boolean  ┆ AreEqual(An ┆ … ┆ true      ┆ false     ┆ []          ┆ []          │
│          ┆      ┆          ┆ gle(O, D,   ┆   ┆           ┆           ┆             ┆             │
│          ┆      ┆          ┆ E), Angle…  ┆   ┆           ┆           ┆             ┆             │
│ 16       ┆ O'   ┆ point    ┆ Reflect(O,  ┆ … ┆ true      ┆ false     ┆ ["O", "P",  ┆ ["f"]       │
│          ┆      ┆          ┆ f)          ┆   ┆           ┆           ┆ … "f"]      ┆             │
│ 17       ┆ C'   ┆ point    ┆ Reflect(C,  ┆ … ┆ true      ┆ false     ┆ ["C", "O",  ┆ ["C"]       │
│          ┆      ┆          ┆ f)          ┆   ┆           ┆           ┆ … "f"]      ┆             │
│ 18       ┆ E'   ┆ point    ┆ Reflect(E,  ┆ … ┆ true      ┆ false     ┆ ["C", "E",  ┆ ["E"]       │
│          ┆      ┆          ┆ f)          ┆   ┆           ┆           ┆ … "g"]      ┆             │
│ 19       ┆ t2   ┆ triangle ┆ Polygon(O', ┆ … ┆ false     ┆ false     ┆ ["C", "C'", ┆ ["C'",      │
│          ┆      ┆          ┆ C', E')     ┆   ┆           ┆           ┆ … "g"]      ┆ "E'", "O'"] │
│ 20       ┆ e'   ┆ segment  ┆ Segment(O', ┆ … ┆ false     ┆ true      ┆ ["C", "C'", ┆ ["C'",      │
│          ┆      ┆          ┆ C', t2)     ┆   ┆           ┆           ┆ … "t2"]     ┆ "O'", "t2"] │
│ 21       ┆ o'   ┆ segment  ┆ Segment(C', ┆ … ┆ false     ┆ true      ┆ ["C", "C'", ┆ ["C'",      │
│          ┆      ┆          ┆ E', t2)     ┆   ┆           ┆           ┆ … "t2"]     ┆ "E'", "t2"] │
│ 22       ┆ c'   ┆ segment  ┆ Segment(E', ┆ … ┆ false     ┆ true      ┆ ["C", "C'", ┆ ["E'",      │
│          ┆      ┆          ┆ O', t2)     ┆   ┆           ┆           ┆ … "t2"]     ┆ "O'", "t2"] │
│ 23       ┆ c    ┆ boolean  ┆ AreEqual(D, ┆ … ┆ true      ┆ false     ┆ []          ┆ []          │
│          ┆      ┆          ┆ E')         ┆   ┆           ┆           ┆             ┆             │
└──────────┴──────┴──────────┴─────────────┴───┴───────────┴───────────┴─────────────┴─────────────┘

In [35]:
nx.write_network_text(build_graph_from_df(p.df, reduce_transitive=True))

╟── eq1
╎   ├─╼ O
╎   │   └─╼ f ╾ P
╎   │       ├─╼ C
╎   │       │   ├─╼ C'
╎   │       │   │   └─╼ t2 ╾ O', E'
╎   │       │   │       ├─╼ o'
╎   │       │   │       ├─╼ e'
╎   │       │   │       └─╼ c'
╎   │       │   └─╼ g
╎   │       │       ├─╼ E
╎   │       │       │   ├─╼ t1 ╾ D
╎   │       │       │   │   ├─╼ d
╎   │       │       │   │   ├─╼ e
╎   │       │       │   │   └─╼ o
╎   │       │       │   └─╼ E'
╎   │       │       │       └─╼  ...
╎   │       │       └─╼ D
╎   │       │           └─╼  ...
╎   │       ├─╼ B
╎   │       ├─╼ O'
╎   │       │   └─╼  ...
╎   │       └─╼ A
╎   └─╼ P
╎       └─╼  ...
╟── a
╟── b
╙── c

In [ ]:
ｖ

In [9]:
from itertools import zip_longest

l0 = range(10)
await ggb.function("setLayerVisible", list(zip_longest(list(l0), [], fillvalue=False)))
l0 = [9, 0]
await ggb.function("setLayerVisible", list(zip_longest(list(l0), [], fillvalue=True)))

[None, None]

In [10]:
# case 3 of interactions: XML attributes

In [11]:
r = await ggb.function("getXML", ['A'])
print(r)

<element type="point" label="A">
	<show object="true" label="true" ev="4"/>
	<objColor r="176" g="0" b="32" alpha="0"/>
	<layer val="9"/>
	<labelMode val="0"/>
	<animation step="0.1" type="1" playing="false"/>
	<pointSize val="5"/>
	<pointStyle val="0"/>
	<coords x="10" y="0" z="1"/>
</element>

In [12]:
o2 = c.ggb_schema.decode(r)
o2

{'@type': 'point',
 '@label': 'A',
 'show': [{'@object': True, '@label': True, '@ev': 4}],
 'objColor': [{'@r': 176, '@g': 0, '@b': 32, '@alpha': 0.0}],
 'layer': [{'@val': 9}],
 'labelMode': [{'@val': 0}],
 'animation': [{'@step': '0.1', '@type': 1, '@playing': False}],
 'pointSize': [{'@val': 5.0}],
 'pointStyle': [{'@val': 0}],
 'coords': [{'@x': '10', '@y': '0', '@z': '1'}]}

In [13]:
o2['show'][0]['@object'] = False
o2

{'@type': 'point',
 '@label': 'A',
 'show': [{'@object': False, '@label': True, '@ev': 4}],
 'objColor': [{'@r': 176, '@g': 0, '@b': 32, '@alpha': 0.0}],
 'layer': [{'@val': 9}],
 'labelMode': [{'@val': 0}],
 'animation': [{'@step': '0.1', '@type': 1, '@playing': False}],
 'pointSize': [{'@val': 5.0}],
 'pointStyle': [{'@val': 0}],
 'coords': [{'@x': '10', '@y': '0', '@z': '1'}]}

In [14]:
# construct xml attributes from dict
x = xmlschema.etree_tostring(c.ggb_schema.encode(o2, 'element'))
print(x)

<element type="point" label="A">
    <show object="false" label="true" ev="4" />
    <objColor r="176" g="0" b="32" alpha="0.0" />
    <layer val="9" />
    <labelMode val="0" />
    <animation step="0.1" type="1" playing="false" />
    <pointSize val="5.0" />
    <pointStyle val="0" />
    <coords x="10" y="0" z="1" />
</element>

In [15]:
# update the applet
r = await ggb.function("evalXML", [x])

In [9]:
from itertools import zip_longest

l0 = range(10)
await ggb.function("setLayerVisible", list(zip_longest(list(l0), [], fillvalue=False)))
l0 = [9, 0]
await ggb.function("setLayerVisible", list(zip_longest(list(l0), [], fillvalue=True)))

[None, None]

In [10]:
# case 3 of interactions: XML attributes

In [11]:
r = await ggb.function("getXML", ['A'])
print(r)

<element type="point" label="A">
	<show object="true" label="true" ev="4"/>
	<objColor r="176" g="0" b="32" alpha="0"/>
	<layer val="9"/>
	<labelMode val="0"/>
	<animation step="0.1" type="1" playing="false"/>
	<pointSize val="5"/>
	<pointStyle val="0"/>
	<coords x="10" y="0" z="1"/>
</element>

In [12]:
o2 = c.ggb_schema.decode(r)
o2

{'@type': 'point',
 '@label': 'A',
 'show': [{'@object': True, '@label': True, '@ev': 4}],
 'objColor': [{'@r': 176, '@g': 0, '@b': 32, '@alpha': 0.0}],
 'layer': [{'@val': 9}],
 'labelMode': [{'@val': 0}],
 'animation': [{'@step': '0.1', '@type': 1, '@playing': False}],
 'pointSize': [{'@val': 5.0}],
 'pointStyle': [{'@val': 0}],
 'coords': [{'@x': '10', '@y': '0', '@z': '1'}]}

In [13]:
o2['show'][0]['@object'] = False
o2

{'@type': 'point',
 '@label': 'A',
 'show': [{'@object': False, '@label': True, '@ev': 4}],
 'objColor': [{'@r': 176, '@g': 0, '@b': 32, '@alpha': 0.0}],
 'layer': [{'@val': 9}],
 'labelMode': [{'@val': 0}],
 'animation': [{'@step': '0.1', '@type': 1, '@playing': False}],
 'pointSize': [{'@val': 5.0}],
 'pointStyle': [{'@val': 0}],
 'coords': [{'@x': '10', '@y': '0', '@z': '1'}]}

In [14]:
# construct xml attributes from dict
x = xmlschema.etree_tostring(c.ggb_schema.encode(o2, 'element'))
print(x)

<element type="point" label="A">
    <show object="false" label="true" ev="4" />
    <objColor r="176" g="0" b="32" alpha="0.0" />
    <layer val="9" />
    <labelMode val="0" />
    <animation step="0.1" type="1" playing="false" />
    <pointSize val="5.0" />
    <pointStyle val="0" />
    <coords x="10" y="0" z="1" />
</element>

In [15]:
# update the applet
r = await ggb.function("evalXML", [x])

In [16]:
r = await ggb.function("getBase64")

In [17]:
type(r), type(r.encode('ascii'))

(str, bytes)

In [18]:
# encode str to bytes for save
ggb.construction.base64_buffer = r.encode('ascii')
# ggb.construction.base64_buffer

In [19]:
# using API, some part of archive would lost...
c.save()